image: Visual Studio 2017

shallow_clone: true

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc14/
    - appveyor.yml

environment:
  BOOST_ROOT: C:\Libraries\boost_1_65_1

install:
  - ps: if (-not (Test-Path 0.1)) { Start-FileDownload https://github.com/rubyserver/trs-sdk/archive/0.1.zip; 7z x 0.1.zip }
  - set TRSSDKDir=%CD%\0.1

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - 0.1 -> appveyor.yml

artifacts:
  - path: vc14\**\therubyserver.exe
